sudo: required
services:
  - docker

before_install:
  - docker build -t shubhamsingal07/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shubhamsingal07/react-test npm test

after_success:
  - docker build -t shubhamsingal07/multi-client ./client
  - docker build -t shubhamsingal07/multi-nginx ./nginx
  - docker build -t shubhamsingal07/multi-server ./server
  - docker build -t shubhamsingal07/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push shubhamsingal07/multi-client
  - docker push shubhamsingal07/multi-nginx
  - docker push shubhamsingal07/multi-server
  - docker push shubhamsingal07/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: us-west-1
    app: multi-docker
    env: MultiDocker-env
    bucket-name: elasticbeanstalk-us-west-1-.....
    bucket_path: docker-multi
    on: 
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY
